//$(".fxc-dropdown-option, .azc-optionPicker-item")
export const GLOSSARY_TERMS = [
  "access token",
  "application id",
  "client id",
  "application manifest",
  "application object",
  "application registration",
  "authorization code",
  "authorization endpoint",
  "authorization grant",
  "authorization server",
  "claim",
  "client application",
  "confidential client",
  "consent",
  "id token",
  "Microsoft identity platform",
  "multi-tenant application",
  "native client",
  "permissions",
  "refresh token",
  "resource owner",
  "resource server",
  "roles",
  "scopes",
  "security token",
  "service principal object",
  "sign in",
  "sign out",
  "tenant",
  "token endpoint",
  "User-agent-based client",
  "user principal",
  "web client",
  "Next steps",
];
